service:
  name: forms-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  profile: andismith
  runtime: nodejs10

functions:
  contact:
    handler: src/api/contact/handler.post
    events:
      - http:
          method: post
          path: contact
